services:
  mariadb:
    extends:
      file: ./mariadb/docker-compose.yml
      service: mariadb
    networks:
      - broadcaster0
  bedrockconnect:
    extends:
      file: ./bedrockconnect/docker-compose.yml
      service: bedrockconnect
    networks:
      - broadcaster0
  mcxboxbroadcast:
    extends:
      file: ./mcxboxbroadcast/docker-compose.yml
      service: mcxboxbroadcast
    networks:
      - broadcaster0

# Hotfix for MTU mismatch between Wireguard and Docker, 
# remove once proper fix is applied to machine.
networks:
  broadcaster0:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1420

volumes:
  mariadb_data:
