services:
  bedrockconnect:
    extends:
      file: ./bedrockconnect/docker-compose.yml
      service: bedrockconnect
  mariadb:
    extends:
      file: ./mariadb/docker-compose.yml
      service: mariadb
  mcxboxbroadcast:
    extends:
      file: ./mcxboxbroadcast/docker-compose.yml
      service: mcxboxbroadcast

volumes:
  mariadb_data:
